# Generated by Django 3.2.13 on 2022-07-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterperiod',
            name='enter_inputs',
            field=models.BooleanField(default=True),
        ),
    ]
